/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorDirectorio;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ariel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ControladorDirectorio controlador;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRuta = new javax.swing.JTextField();
        jButtonListarArchivos = new javax.swing.JButton();
        jButtonListarArchivosOcultos = new javax.swing.JButton();
        jButtonListarDirectoriosOcultos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonListarDirectorios = new javax.swing.JButton();
        JmenuBarPrincipal = new javax.swing.JMenuBar();
        fileMenuGestionarDirectorio = new javax.swing.JMenu();
        JMenuItemCrear = new javax.swing.JMenuItem();
        JMenuItemEliminar = new javax.swing.JMenuItem();
        JMenuItemRenombrar = new javax.swing.JMenuItem();
        JMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Arichivos UPS");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(42, 131, 154));

        jListArchivos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListArchivos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jListArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListArchivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListArchivos);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("Ruta:");

        jTextFieldRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRutaMouseClicked(evt);
            }
        });

        jButtonListarArchivos.setText("Listar Archivos");
        jButtonListarArchivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarArchivosActionPerformed(evt);
            }
        });

        jButtonListarArchivosOcultos.setText("Listar Archivos Ocultos");
        jButtonListarArchivosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarArchivosOcultosActionPerformed(evt);
            }
        });

        jButtonListarDirectoriosOcultos.setText("Listar Directorios Ocultos");
        jButtonListarDirectoriosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDirectoriosOcultosActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(42, 131, 154));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 1, 21))); // NOI18N
        jScrollPane2.setViewportView(jTextArea1);

        jButtonListarDirectorios.setText("Listar Directorios");
        jButtonListarDirectorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDirectoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jButtonListarDirectorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListarArchivosOcultos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListarDirectoriosOcultos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonListarArchivos)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarArchivos)
                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarDirectoriosOcultos)
                    .addComponent(jButtonListarArchivosOcultos)
                    .addComponent(jButtonListarDirectorios))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        JmenuBarPrincipal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        fileMenuGestionarDirectorio.setMnemonic('f');
        fileMenuGestionarDirectorio.setText("Gestionar Directorio");
        fileMenuGestionarDirectorio.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        JMenuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemCrear.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemCrear.setMnemonic('o');
        JMenuItemCrear.setText("Crear");
        JMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCrearActionPerformed(evt);
            }
        });
        fileMenuGestionarDirectorio.add(JMenuItemCrear);

        JMenuItemEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemEliminar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemEliminar.setMnemonic('s');
        JMenuItemEliminar.setText("Eliminar");
        fileMenuGestionarDirectorio.add(JMenuItemEliminar);

        JMenuItemRenombrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemRenombrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemRenombrar.setMnemonic('a');
        JMenuItemRenombrar.setText("Renombrar");
        fileMenuGestionarDirectorio.add(JMenuItemRenombrar);

        JMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemSalir.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemSalir.setMnemonic('x');
        JMenuItemSalir.setText("Salir");
        JMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSalirActionPerformed(evt);
            }
        });
        fileMenuGestionarDirectorio.add(JMenuItemSalir);

        JmenuBarPrincipal.add(fileMenuGestionarDirectorio);

        setJMenuBar(JmenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItemSalirActionPerformed

    private void JMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCrearActionPerformed
        controlador = new ControladorDirectorio(jTextFieldRuta.getText());
        if (controlador.getArchivo() != null) {
            String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre", "Crear Directrio", HEIGHT);
            if (controlador.crearDirectorio(nombre)) {
                JOptionPane.showMessageDialog(this, "Directorio creado");
                jListArchivos.setModel(controlador.listarDirectorios());
                
            } else {
                JOptionPane.showMessageDialog(this, "Ya existe un directorio con ese nombre");
                
            }
        } else { 
            JOptionPane.showMessageDialog(this, "La ruta ingresada no existe");
        }
    }//GEN-LAST:event_JMenuItemCrearActionPerformed

    private void jButtonListarDirectoriosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDirectoriosOcultosActionPerformed
        controlador = new ControladorDirectorio(jTextFieldRuta.getText());
        if (controlador.listarDirectoriosOcultos()!= null) {
            jListArchivos.setModel(controlador.listarDirectoriosOcultos());
        } else {
            JOptionPane.showMessageDialog(this, "La ruta ingresada no existe");
        }
    }//GEN-LAST:event_jButtonListarDirectoriosOcultosActionPerformed

    private void jButtonListarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarArchivosActionPerformed
        controlador = new ControladorDirectorio(jTextFieldRuta.getText());
        if (controlador.listarArchivos()!= null) {
            jListArchivos.setModel(controlador.listarArchivos());
        } else {
            JOptionPane.showMessageDialog(this, "La ruta ingresada no existe");
        }
        
    }//GEN-LAST:event_jButtonListarArchivosActionPerformed

    private void jButtonListarArchivosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarArchivosOcultosActionPerformed
        controlador = new ControladorDirectorio(jTextFieldRuta.getText());
        if (controlador.listarArchivosOcultos()!= null) {
            jListArchivos.setModel(controlador.listarArchivosOcultos());
        } else {
            JOptionPane.showMessageDialog(this, "La ruta ingresada no existe");
        }
    }//GEN-LAST:event_jButtonListarArchivosOcultosActionPerformed

    private void jButtonListarDirectoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDirectoriosActionPerformed
        controlador = new ControladorDirectorio(jTextFieldRuta.getText());
        if (controlador.listarDirectorios()!= null) {
            jListArchivos.setModel(controlador.listarDirectorios());
        } else {
            JOptionPane.showMessageDialog(this, "La ruta ingresada no existe");
        }
    }//GEN-LAST:event_jButtonListarDirectoriosActionPerformed

    private void jListArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListArchivosMouseClicked
        jTextArea1.setText(controlador.mostrarInformacion(jTextFieldRuta.getText() + jListArchivos.getSelectedValue()));
      
    }//GEN-LAST:event_jListArchivosMouseClicked

    private void jTextFieldRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRutaMouseClicked

        limpiar();
    }//GEN-LAST:event_jTextFieldRutaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    public void limpiar() {
        jListArchivos.setModel(new DefaultListModel<>());
        jTextArea1.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemCrear;
    private javax.swing.JMenuItem JMenuItemEliminar;
    private javax.swing.JMenuItem JMenuItemRenombrar;
    private javax.swing.JMenuItem JMenuItemSalir;
    private javax.swing.JMenuBar JmenuBarPrincipal;
    private javax.swing.JMenu fileMenuGestionarDirectorio;
    private javax.swing.JButton jButtonListarArchivos;
    private javax.swing.JButton jButtonListarArchivosOcultos;
    private javax.swing.JButton jButtonListarDirectorios;
    private javax.swing.JButton jButtonListarDirectoriosOcultos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldRuta;
    // End of variables declaration//GEN-END:variables

}
