/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

/**
 *
 * @author ariel
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListArchivos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldRuta = new javax.swing.JTextField();
        jButtonListarDirectorios = new javax.swing.JButton();
        jButtonListarArchivosOcultos = new javax.swing.JButton();
        jButtonListarDirectoriosOcultos = new javax.swing.JButton();
        jButtonMostrerInformacion = new javax.swing.JButton();
        jPanelInformacion = new javax.swing.JPanel();
        jLabelPathAbsoluto = new javax.swing.JLabel();
        jLabelTamañoDelArchivo = new javax.swing.JLabel();
        jLabelPermisosDeLectura = new javax.swing.JLabel();
        jLabelPermisosDeEscritura = new javax.swing.JLabel();
        jLabelFechaUltimaModificacion = new javax.swing.JLabel();
        jTextFieldPathAbsoluto = new javax.swing.JTextField();
        jTextFieldPermisosDeLectura = new javax.swing.JTextField();
        jTextFieldTamañoDelArchivo = new javax.swing.JTextField();
        jTextFieldPermisosDeEscritura = new javax.swing.JTextField();
        jTextFieldFechaUltimaModificacion = new javax.swing.JTextField();
        JmenuBarPrincipal = new javax.swing.JMenuBar();
        fileMenuGestionarDirectorio = new javax.swing.JMenu();
        JMenuItemCrear = new javax.swing.JMenuItem();
        JMenuItemEliminar = new javax.swing.JMenuItem();
        JMenuItemRenombrar = new javax.swing.JMenuItem();
        JMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador de Arichivos UPS");
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);

        jPanel1.setBackground(new java.awt.Color(42, 131, 154));

        jListArchivos.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(jListArchivos);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel1.setText("Ruta:");

        jButtonListarDirectorios.setText("Listar Directorios");

        jButtonListarArchivosOcultos.setText("Listar Archivos Ocultos");

        jButtonListarDirectoriosOcultos.setText("Listar Directorios Ocultos");
        jButtonListarDirectoriosOcultos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarDirectoriosOcultosActionPerformed(evt);
            }
        });

        jButtonMostrerInformacion.setText("Mostrar Informacion");

        jPanelInformacion.setBackground(new java.awt.Color(42, 131, 154));
        jPanelInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Informacion", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial Narrow", 1, 21))); // NOI18N

        jLabelPathAbsoluto.setText("Path absoluto:");

        jLabelTamañoDelArchivo.setText("Tamaño del archivo:");

        jLabelPermisosDeLectura.setText("Permisos de lectura:");

        jLabelPermisosDeEscritura.setText("Permisos de escritura:");

        jLabelFechaUltimaModificacion.setText("Fecha ultima modificacion:");

        jTextFieldPathAbsoluto.setEditable(false);

        jTextFieldPermisosDeLectura.setEditable(false);

        jTextFieldTamañoDelArchivo.setEditable(false);

        jTextFieldPermisosDeEscritura.setEditable(false);

        jTextFieldFechaUltimaModificacion.setEditable(false);

        javax.swing.GroupLayout jPanelInformacionLayout = new javax.swing.GroupLayout(jPanelInformacion);
        jPanelInformacion.setLayout(jPanelInformacionLayout);
        jPanelInformacionLayout.setHorizontalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelPathAbsoluto)
                        .addGap(74, 74, 74)
                        .addComponent(jTextFieldPathAbsoluto))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelFechaUltimaModificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFechaUltimaModificacion, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelPermisosDeLectura)
                        .addGap(38, 38, 38)
                        .addComponent(jTextFieldPermisosDeLectura, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelTamañoDelArchivo)
                        .addGap(38, 38, 38)
                        .addComponent(jTextFieldTamañoDelArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(jLabelPermisosDeEscritura)
                        .addGap(27, 27, 27)
                        .addComponent(jTextFieldPermisosDeEscritura, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInformacionLayout.setVerticalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPathAbsoluto)
                    .addComponent(jTextFieldPathAbsoluto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamañoDelArchivo)
                    .addComponent(jTextFieldTamañoDelArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPermisosDeLectura)
                    .addComponent(jTextFieldPermisosDeLectura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPermisosDeEscritura)
                    .addComponent(jTextFieldPermisosDeEscritura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaUltimaModificacion)
                    .addComponent(jTextFieldFechaUltimaModificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanelInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(380, 380, 380)
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jButtonListarDirectorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonListarArchivosOcultos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonListarDirectoriosOcultos)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonMostrerInformacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonListarDirectorios)
                    .addComponent(jButtonListarArchivosOcultos)
                    .addComponent(jButtonListarDirectoriosOcultos))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMostrerInformacion)
                .addGap(21, 21, 21))
        );

        JmenuBarPrincipal.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        fileMenuGestionarDirectorio.setMnemonic('f');
        fileMenuGestionarDirectorio.setText("Gestionar Directorio");
        fileMenuGestionarDirectorio.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N

        JMenuItemCrear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemCrear.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemCrear.setMnemonic('o');
        JMenuItemCrear.setText("Crear");
        JMenuItemCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemCrearActionPerformed(evt);
            }
        });
        fileMenuGestionarDirectorio.add(JMenuItemCrear);

        JMenuItemEliminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemEliminar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemEliminar.setMnemonic('s');
        JMenuItemEliminar.setText("Eliminar");
        fileMenuGestionarDirectorio.add(JMenuItemEliminar);

        JMenuItemRenombrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemRenombrar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemRenombrar.setMnemonic('a');
        JMenuItemRenombrar.setText("Renombrar");
        fileMenuGestionarDirectorio.add(JMenuItemRenombrar);

        JMenuItemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, java.awt.event.InputEvent.CTRL_MASK));
        JMenuItemSalir.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        JMenuItemSalir.setMnemonic('x');
        JMenuItemSalir.setText("Salir");
        JMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSalirActionPerformed(evt);
            }
        });
        fileMenuGestionarDirectorio.add(JMenuItemSalir);

        JmenuBarPrincipal.add(fileMenuGestionarDirectorio);

        setJMenuBar(JmenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_JMenuItemSalirActionPerformed

    private void JMenuItemCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemCrearActionPerformed

    private void jButtonListarDirectoriosOcultosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarDirectoriosOcultosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonListarDirectoriosOcultosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuItemCrear;
    private javax.swing.JMenuItem JMenuItemEliminar;
    private javax.swing.JMenuItem JMenuItemRenombrar;
    private javax.swing.JMenuItem JMenuItemSalir;
    private javax.swing.JMenuBar JmenuBarPrincipal;
    private javax.swing.JMenu fileMenuGestionarDirectorio;
    private javax.swing.JButton jButtonListarArchivosOcultos;
    private javax.swing.JButton jButtonListarDirectorios;
    private javax.swing.JButton jButtonListarDirectoriosOcultos;
    private javax.swing.JButton jButtonMostrerInformacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFechaUltimaModificacion;
    private javax.swing.JLabel jLabelPathAbsoluto;
    private javax.swing.JLabel jLabelPermisosDeEscritura;
    private javax.swing.JLabel jLabelPermisosDeLectura;
    private javax.swing.JLabel jLabelTamañoDelArchivo;
    private javax.swing.JList<String> jListArchivos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldFechaUltimaModificacion;
    private javax.swing.JTextField jTextFieldPathAbsoluto;
    private javax.swing.JTextField jTextFieldPermisosDeEscritura;
    private javax.swing.JTextField jTextFieldPermisosDeLectura;
    private javax.swing.JTextField jTextFieldRuta;
    private javax.swing.JTextField jTextFieldTamañoDelArchivo;
    // End of variables declaration//GEN-END:variables

}
